version: "3.0"

expectations:
  population_size: 1000

actions:
  extract_vaccination_names:
    run: >
      sqlrunner:latest
        --output output/vaccination_names.csv
        analysis/extract_vaccination_names.sql
    outputs:
      moderately_sensitive:
        rows: output/vaccination_names.csv

  vaccination_names_html:
    needs: [extract_vaccination_names]
    run: >
      python:latest 
        jupyter nbconvert analysis/vaccination_names.ipynb 
        --execute 
        --to html 
        --no-input 
        --output-dir=/workspace/output 
        --ExecutePreprocessor.timeout=86400
    outputs:
      moderately_sensitive:
        html: output/vaccination_names.html
        
  extract_covid_vaccination_name_frequency:
    run: >
      sqlrunner:latest
        --output output/covid_vaccination_name_frequency.csv
        analysis/extract_covid_vaccination_name_frequency.sql
    outputs:
      moderately_sensitive:
        rows: output/covid_vaccination_name_frequency.csv
